create table users (
    id bigint generated by default as identity,
    email varchar(100) not null,
    password varchar(255) not null,
    nickname varchar(30) not null,
    age integer not null,
    gender varchar(20) not null,
    region varchar(100) not null,
    position varchar(20) not null,
    skill_level varchar(100),
    career varchar(500),
    video_url varchar(500),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint pk_users primary key (id),
    constraint uk_users_email unique (email)
);

create table teams (
    id bigint generated by default as identity,
    owner_user_id bigint not null,
    name varchar(100) not null,
    logo_url varchar(500),
    home_region varchar(100) not null,
    home_stadium varchar(100),
    age_group varchar(50) not null,
    level varchar(20) not null,
    fee integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint pk_teams primary key (id),
    constraint fk_teams_owner_user foreign key (owner_user_id) references users (id)
);

create table posts (
    id bigint generated by default as identity,
    author_user_id bigint not null,
    team_id bigint,
    board_type varchar(30) not null,
    role_type varchar(30) not null,
    status varchar(30) not null,
    title varchar(100) not null,
    match_date timestamp(6),
    location varchar(200),
    content text not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint pk_posts primary key (id),
    constraint fk_posts_author_user foreign key (author_user_id) references users (id),
    constraint fk_posts_team foreign key (team_id) references teams (id)
);

create index idx_teams_owner_user_id on teams (owner_user_id);
create index idx_posts_author_user_id on posts (author_user_id);
create index idx_posts_team_id on posts (team_id);
create index idx_posts_board_role_status on posts (board_type, role_type, status);
create index idx_posts_match_date on posts (match_date);
