create table post_applications (
    id bigint generated by default as identity,
    post_id bigint not null,
    applicant_user_id bigint not null,
    status varchar(30) not null,
    message varchar(500),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint pk_post_applications primary key (id),
    constraint fk_post_applications_post foreign key (post_id) references posts (id),
    constraint fk_post_applications_applicant foreign key (applicant_user_id) references users (id),
    constraint uk_post_applications_post_applicant unique (post_id, applicant_user_id)
);

create index idx_post_applications_post_id on post_applications (post_id);
create index idx_post_applications_applicant_user_id on post_applications (applicant_user_id);
create index idx_post_applications_status on post_applications (status);
